### ISSUE TITLE
Wrong duration in calls

### ISSUE THREAD

**Issue by ivahaev** [blak3r/yaai#157] opened 2013-10-03 09:24 UTC
Hello,

Yaai version 3.5.5 works perfectly but the duration of call writes wrong.
![skitch](https://f.cloud.github.com/assets/5515876/1260512/7abe03d2-2c0d-11e3-815f-5bb7ba1a8965.png)

How can I fix it?

Regards, 
ivahaev

**Comment by blak3r** [comment] 2013-10-04 01:46
That's a good question... hmm... most likely timezone related.
Is the date start and date end times correct?

P.S. - that theme looks pretty cool.  What is that?

**Comment by ivahaev** [comment] 2013-10-04 03:15
The theme is standart comes with SugarCRM 6.5.1.
Where can I look date end?

Call screen:
![2013-10-04 09 19 14](https://f.cloud.github.com/assets/5515876/1267002/d493f7c2-2ca3-11e3-8c2a-1a802f8cd49a.png)

**Comment by ivahaev** [comment] 2013-10-07 04:47
Hi blak3r,

Can you help me or not?

**Comment by blak3r** [comment] 2013-10-07 13:54
Go to call detail view

**Comment by ivahaev** [comment] 2013-10-07 15:10
Sorry, the last message contains detail view screenshot.
Do you need another view?

**Comment by blak3r** [comment] 2013-10-07 17:01
Sorry, i didn't see the screenshot.
Umm... so The created time is 5:19pm
The start time is 9:19pm.

So, it's a timezone issue.

I'm not sure why it's a negative number though... I'd think the end time would show as 9:43pm... Check the timezone you have set in php.ini... that's probably the issue.

**Comment by ivahaev** [comment] 2013-10-07 17:06
Hmm. php.ini..
Ok I'll try.
thank you

**Comment by ivahaev** [comment] 2013-10-07 17:35
I've set timezone in php.ini. No effect!
The settings in php.ini and settings are the same.

**Comment by blak3r** [comment] 2013-10-07 17:57
Weird... I'd have to think really hard about what is happening.  There is a
thread on here about timezones.  Maybe if you read that it'll give you some
ideas.

Does your sugarcrm database user have admin credentials?

**Comment by ivahaev** [comment] 2013-10-07 18:16
Let's think about it. Where from "start date&time", "created" and "changed" come? The timezone is UTC+4 (Europe/Moscow), and start time is +4 but from local time.
The timezone was the first thing I looked. 
May be start time comes from asterisk? But asterisk  has the same timezone. 
Brrr...
One solution will be edit asteriskLogger.php near 719 line but it would be wrong and really stupid :)

Ok, I'm going to bed. Tomorrow is a new day.

Thanks for the help.

**Comment by blak3r** [comment] 2013-10-07 18:21
it all comes from UNIX TIME mysql calls.
I think sugar is setting the date modified and date created.

That thread explains why we did it that way.  Had to do with differences in
database time vs. sugar time.

**Comment by blak3r** [comment] 2013-11-06 01:08
@ivahaev did you ever figure out what the problem is? Want to close this thread out if so.

**Comment by blak3r** [comment] 2014-01-17 01:14
closing this thread, please reopen if you have anything else to mention.

**Closed as completed** 2014-01-17 01:14 UTC
