### ISSUE TITLE
Can't X out of Call Popups (when multiple calls windows active)

### ISSUE THREAD

**Issue by mic3009** [blak3r/yaai#15] opened 2012-05-11 08:14 UTC
Hi,
when i get an Inbound call an i close the window, then it pop up again and again. When i write notice in the Box and save it, it is in calls list as an outbound call.
I use 2.03 and Sugar 6.32.

Thank You for your help.
Micha

**Comment by superles** [comment] 2012-05-11 12:31
I have the same problem, but my call not changed direction. And pop up again and again. I tried write notice and save, but pop up again. What interesting , that in calls became created calls with status "Planned" and subject OBC:("notice" that i wrote in pop up notice box).

OBC: afdhsdfh            Planned                 11.05.2012 15:23  
OBC: afdhsdfh            Planned                 11.05.2012 15:23  
OBC: afdhsdfh            Planned                 11.05.2012 15:22  
OBC: sdh             Planned                 11.05.2012 15:15  
OBC: sdh             Planned                 11.05.2012 15:15  
 OBC: sdh            Planned

**Comment by blak3r** [comment] 2012-05-11 18:01
I have seen before call windows refusing to close.  They would keep popping up.  
Typically this would go away after i refreshed the page and since it happened while i was developing it I didn't think much of it.  Is this always happening to you?  It's likely caused by an ajax request failing which tells the server to close the windows.

What browser are you all using?

As for setting the call status to "Planned" are you sure that is my plugin and not just some other junk calls you have?  I never set it to that.  It's either "Held" or "Missed".  Hmm... perhaps Planned is the default state.

**Comment by blak3r** [comment] 2012-05-11 18:02
Also, mic - update to version 2.3.  There are lots of bug fixes in it.

**Comment by superles** [comment] 2012-05-11 20:37
Browser - Chrome 18. Yaai - version 2.3.0.9. I also think that this is due to AJAX requests. But it must be tested.

**Comment by blak3r** [comment] 2012-05-11 21:30
Is this always happening?  Or just sometime?  

Any errors in your logs?

And it doesn't close just when you click the X button or also when you try and save a note.

**Comment by superles** [comment] 2012-05-12 09:38
It happens sometime. More often when i do 2-3 phone calls and try to close all popup window. It does not matter to press x or save. At the same time in the MYSQL - asterisk_log - uistate for these calls is NULL

**Comment by blak3r** [comment] 2012-05-12 15:07
Ok... yeah when i've seen it happen it's when i've had many calls open also.  It seemed like I could click the X on one of them and it would close but the others wouldn't until I hit refresh then I could close another.

**Comment by superles** [comment] 2012-05-13 14:13
At the opening of a large number of popup windows (lots of incoming or outgoing calls) is a big load on the server. When you close some windows server does not have time to process all the records and some records at the close no call_record_id. So when you click on the X no action. Therefore, this expression does not make sense:

else if ($ _REQUEST ['action'] == "setContactId") {
     $ current_language = $ _SESSION ['authenticated_user_language'];
     if (empty ($ current_language)) {
         $ current_language = $ sugar_config ['default_language'];
     }
     require ("custom / modules / Asterisk / language /". $ current_language. ". lang.php");
     $ cUser = new User ();
     $ cUser-> retrieve ($ _SESSION ['authenticated_user_id']);

```
 / / Query log
 / / Very basic santization
 $ contactId = preg_replace ('/ [^ a-z0-9 \ - \.] / i','', $ _REQUEST ['contact_id']); / / mysql_real_escape_string ($ _REQUEST ['ui_state']);
 $ callRecord = preg_replace ('/ [^ a-z0-9 \ - \.] / i','', $ _REQUEST ['call_record']); / / mysql_real_escape_string ($ _REQUEST ['call_record']);
 $ query = "update asterisk_log set contact_id = \" $ contactId \ "where call_record_id = \" $ callRecord \ "";
```

**Comment by blak3r** [comment] 2012-07-30 23:45
I believe this issue has now been resolved in my most recent commit.  I merged your pull request and then expanded similar idea to the saveMemo and setContactId actions as well. 

I'm just reading now your comment about large load on the server when multiple popups.  I don't think that had anything todo with it.

**Closed as completed by blak3r** 2012-07-30 23:45 UTC
Labels: bug
