### ISSUE TITLE
Support for Sugar version 6.5

### ISSUE THREAD

**Issue by edokid** [blak3r/yaai#26] opened 2012-06-17 16:43 UTC
Just tried installing it on 6.5.  All seemed to work well, incoming and outgoing calls work as expected.  However it seems to completely break the Sugar interface.  Like if you type in the search box at the top it doesn't work.  When you hover over Accounts, Opportunities etc it shows 3 columns Actions, Recently Viewed and Favorite, all always empty.  If you click your user name to try and go to Admin it doesn't work at all.  As soon as I disabled yaai Sugar worked fine again.  Is this just due to 6.5 or is that some other issue that might be causing this?  Hope it works soon as so far this is amazing!

**Comment by blak3r** [comment] 2012-06-18 01:17
I haven't tested on 6.5 yet. I've heard that 6.5 nearly breaks all plugins. 

I've been traveling for last 2 weeks. So, gonna be long while until I can test myself. 

Let me know if you figure it out. Probably related to jQuery being included by default in 6.5. 

~blake

**Comment by edokid** [comment] 2012-06-18 16:39
Will do thanks for the reply.  I probably won't get to test it much since I'm not that technical and it makes the system unusable.  Just wanted to make sure that it wasn't just a config issue that was causing it but really love it when it works!

**Comment by blak3r** [comment] 2012-06-30 07:13
@edokid I got 6.5 installed tonight.  By the time I got through the install process I didn't have much time to play around.  I didn't experience any of the issues you had.  I did however get this error when call popups showed up in a message box.

"Call Record ID returned from server is -1, unable to save call notes for Blak Robertson - 'Ringing"'

Do you have any other plugins loaded?  My 6.5.0 is the GA version and the only plugin installed is yaai

**Comment by blak3r** [comment] 2012-07-02 05:53
I determined the error I was getting was b/c of soap errors.

Apparently in 6.5 they changed the way passwords are hashed in the database.

I posted a question about how to get around this here: http://developers.sugarcrm.com/wordpress/2012/05/16/new-for-sugar-6-5-%E2%80%93-stronger-password-storage-encryption/

```
"My plugin grabs the user_hash directly from the database and then uses this hash when logging in via SOAP api.  This used to work since it was hashed in md5.  As of 6.5, I get incorrect username and password errors.

Anyway to make the SOAP Login method accept the crypt hash from database?

I'm still using the legacy soap.php"
```

**Comment by fromredtogreen** [comment] 2012-07-05 09:54
Hi guys, Sugar is a PITA. This is truly one of the most useful mods I have seen and the only one I am interested in using yet Sugar 5 seems to break it. I am having the same issues. I appreciate you are really busy but if you could take a look at this I (and a lot of others I am sure) would appreciate it. I have an asterisk and a sugar 5 box ready to go if you would like access to test/play? Thanks for your efforts on this project. Tony

**Comment by blak3r** [comment] 2012-07-06 06:49
@fromredtogreen I just committed some fixes for 6.5 to a branch called Sugar6.5.  Here's the commit diff: https://github.com/blak3r/yaai/commit/74864e6d9f911503fcfdff490b582e952dc8450d

As far as I can tell, once those couple changes are made everything should work.

You need to manually edit your config.override.php file and add a line like:

```
$sugar_config['asterisk_soappass'] = 'YOUR_PASSWORD';
```

Eventually, I'll have to add that setting to the configuration page... but don't really want to as it'll be displayed in plaintext.  I wish they hadn't changed the behavior.

**Comment by fromredtogreen** [comment] 2012-07-06 08:37
OK, I am by no means an expert but uninstalled, re-installed the new
version.

Set the config.overide line. UID=soap, PWD = soap (to test) and it seems to
struggle logging in. Checked soap.php and all seems to be working fine.

I changed the UID to root and the same problem, see below

Any ideas?

*******\* Asterisk Logger Starting **************

# Sugar root set to [/var/www/html/custom/modules/Asterisk/../../../]

PHP Notice:  Undefined index: asterisk_log_file in
/var/www/html/custom/modules/Asterisk/asteriskLogger.php on line 118
Logging to:

# Callout prefix is [1]

# Callin prefix is [+1]

asteriskMatchInternal = /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i

# (Config processed)

Selecting DB Name: sugarcrm
! Trying SOAP login endpoint=[http://crm.netboosterusa.com/soap.php]
user=[root] password=[61d61ac5cd80253e21a9a0f050dd40ee]
PHP Warning:  Attempt to modify property of non-object in
/var/www/html/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in
/var/www/html/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in
/var/www/html/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in
/var/www/html/include/nusoap/nusoap.php on line 6160
! Soap login failed!
Array
(
    [id] => -1
    [error] => Array
        (
            [number] => 10
            [name] => Invalid Login
            [description] => Login attempt failed please check the username
and password
        )

)
! FATAL: SOAP login failed, something didnt get set by login... check your
site_url:-1 user=root GUID=-1

On 6 July 2012 07:49, Blake Robertson <
reply@reply.github.com

**Comment by blak3r** [comment] 2012-07-06 16:05
@fromredtogreen How did you install the new version?  I didn't release a new version on sugarforge.  

What you should do is install it by going to the code tab, selecting the Sugar6.5 Branch, then download a zip file.  I think you can then install that version using the module loader.

Alternatively, are you sure your SOAP username and password are correct?

**Comment by fromredtogreen** [comment] 2012-07-06 16:07
Sorry, my terminology. That's exactly what I did.

It's up now with a few minor errors. I figured out the user was a sugar
user not a Linux one.

Thanks for your efforts with this project, it's really appreciated.

Tony

---

Tony Redfearn
UK Technology Team

*Tel: *+442078029511
*Cell: *+447557472648
*E-mail: *tony.redfearn@netbooster.com
*Web: *www.netbooster.co.ukhttp://signature.netbooster.com/www.netbooster.co.uk

_Follow Us:_  http://www.facebook.com/pages/NetBooster-Group/191854004194834?sk=infohttps://twitter.com/#!/NetboosterGroup

_Netbooster UK - Cornwall_
Pool Innovation Centre
Trevenson Road, Pool, Redruth
Cornwall, TR15 3PL, UK

_Tel: +442078029500_
*Web: *www.netbooster.co.ukhttp://signature.netbooster.com/www.netbooster.co.uk

---

Guava Limited is registered in England number 3538849. Registered Office:
Lowin House, Tregolls Road, Truro, Cornwall, TR1 2NA.
Guava Limited is a subsidiary of NetBooster A/S.
This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please contact us.
The content of this email does not necessarily reflect the views or
opinions of Guava Limited.

On 6 July 2012 17:05, Blake Robertson <
reply@reply.github.com

**Comment by blak3r** [comment] 2012-07-06 16:13
@fromredtogreen great, so what are the minor issues that are still happening in 6.5?

**Comment by fromredtogreen** [comment] 2012-07-06 16:14
I am not sure if these can be ignored or are things to be looked at?

# Sugar root set to [/var/www/html/custom/modules/Asterisk/../../../]

PHP Notice:  Undefined index: asterisk_log_file in
/var/www/html/custom/modules/Asterisk/asteriskLogger.php on line 118
Logging to:

# Callout prefix is []

# Callin prefix is [+1]

asteriskMatchInternal = /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i

# (Config processed)

Selecting DB Name: sugarcrm
! Trying SOAP login endpoint=[http://crm.netboosterusa.com/soap.php]
user=[TonyR] password=[###redacted###]
PHP Warning:  Attempt to modify property of non-object in
/var/www/html/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in
/var/www/html/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in
/var/www/html/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in
/var/www/html/include/nusoap/nusoap.php on line 6160
! Successful SOAP login id=kr58f8vt0rrg8l0g6ijvam3ae1 user=TonyR
GUID=39b37065-2df2-e557-0b97-4ff41baf44a5

# Successfully opened socket connection to 209.177.145.234:5038

! AMI Login action returned with rc=Asterisk Call Manager/1.1

PHP Warning:  date(): It is not safe to rely on the system's timezone
settings. You are _required_ to use the date.timezone setting or the
date_default_timezone_set() function. In case you used any of those methods
and you are still getting this warning, you most likely misspelled the
timezone identifier. We selected 'America/New_York' for 'EDT/-4.0/DST'
instead in /var/www/html/custom/modules/Asterisk/asteriskLogger.php on line
984
[2012-07-06 12:13:46]

---

Tony Redfearn
UK Technology Team

*Tel: *+442078029511
*Cell: *+447557472648
*E-mail: *tony.redfearn@netbooster.com
*Web: *www.netbooster.co.ukhttp://signature.netbooster.com/www.netbooster.co.uk

_Follow Us:_  http://www.facebook.com/pages/NetBooster-Group/191854004194834?sk=infohttps://twitter.com/#!/NetboosterGroup

_Netbooster UK - Cornwall_
Pool Innovation Centre
Trevenson Road, Pool, Redruth
Cornwall, TR15 3PL, UK

_Tel: +442078029500_
*Web: *www.netbooster.co.ukhttp://signature.netbooster.com/www.netbooster.co.uk

---

Guava Limited is registered in England number 3538849. Registered Office:
Lowin House, Tregolls Road, Truro, Cornwall, TR1 2NA.
Guava Limited is a subsidiary of NetBooster A/S.
This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please contact us.
The content of this email does not necessarily reflect the views or
opinions of Guava Limited.

On 6 July 2012 17:13, Blake Robertson <
reply@reply.github.com

**Comment by blak3r** [comment] 2012-07-06 16:17
The nusoap one you can ignore.

The date() one is something you should fix by defining your timezone in your php.ini.  If you google that error, you should find a good guide.

**Comment by fromredtogreen** [comment] 2012-07-06 16:19
Thanks!

This mod and your support really are excellent.

---

Tony Redfearn
UK Technology Team

*Tel: *+442078029511
*Cell: *+447557472648
*E-mail: *tony.redfearn@netbooster.com
*Web: *www.netbooster.co.ukhttp://signature.netbooster.com/www.netbooster.co.uk

_Follow Us:_  http://www.facebook.com/pages/NetBooster-Group/191854004194834?sk=infohttps://twitter.com/#!/NetboosterGroup

_Netbooster UK - Cornwall_
Pool Innovation Centre
Trevenson Road, Pool, Redruth
Cornwall, TR15 3PL, UK

_Tel: +442078029500_
*Web: *www.netbooster.co.ukhttp://signature.netbooster.com/www.netbooster.co.uk

---

Guava Limited is registered in England number 3538849. Registered Office:
Lowin House, Tregolls Road, Truro, Cornwall, TR1 2NA.
Guava Limited is a subsidiary of NetBooster A/S.
This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please contact us.
The content of this email does not necessarily reflect the views or
opinions of Guava Limited.

On 6 July 2012 17:17, Blake Robertson <
reply@reply.github.com

**Comment by edokid** [comment] 2012-07-08 21:21
Is there going to be a new release that fixes the issue?  I'm not technical at all so I have no idea what you guys are talking about in these posts or what I'm supposed to do to make it work....

**Comment by blak3r** [comment] 2012-07-08 21:50
@redtogreen think you could provide some instructions for edokid?

I'm not planning on making a new release in the next couple weeks.  Haven't
figured out the best way to hide the SOAP credentials yet.

On Sun, Jul 8, 2012 at 5:21 PM, edokid <
reply@reply.github.com

**Comment by fromredtogreen** [comment] 2012-07-09 07:48
@Blake, I think the instructions you have provided are clear enough. The
bottom line is if you can't understand them don't install this mod. That's
not being rude, just a reflection of the level of skill required for this
mod. The Sugar side is a breeze, if you don't know Asterisk though you are
sunk. Having said that I used the FreePBX distro which is all simple GUI
based and works right our of the box as an ISO.

On the password, I think from a users perspective just add it into the
admin settings. The risk is minimal. However, and I am not sure if this is
possible, when the script is run prompt for the password and keep it
persistent in memory?? If its run in the foreground it's obvious if it
isn't running.

---

Tony Redfearn
UK Technology Team

*Tel: *+442078029511
*Cell: *+447557472648
*E-mail: *tony.redfearn@netbooster.com
*Web: *www.netbooster.co.ukhttp://signature.netbooster.com/www.netbooster.co.uk

_Follow Us:_  http://www.facebook.com/pages/NetBooster-Group/191854004194834?sk=infohttps://twitter.com/#!/NetboosterGroup

_Netbooster UK - Cornwall_
Pool Innovation Centre
Trevenson Road, Pool, Redruth
Cornwall, TR15 3PL, UK

_Tel: +442078029500_
*Web: *www.netbooster.co.ukhttp://signature.netbooster.com/www.netbooster.co.uk

---

Guava Limited is registered in England number 3538849. Registered Office:
Lowin House, Tregolls Road, Truro, Cornwall, TR1 2NA.
Guava Limited is a subsidiary of NetBooster A/S.
This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please contact us.
The content of this email does not necessarily reflect the views or
opinions of Guava Limited.

On 8 July 2012 22:50, Blake Robertson <
reply@reply.github.com

**Comment by blak3r** [comment] 2012-07-09 16:22
@fromredtogreen I guess I was thinking a little how do I install YAAI from a github dev branch.  The process of making a zip file.  Would be a good addition to the Wiki Pages +1 for screenshots heh.

**Comment by sayantandas** [comment] 2012-07-16 17:31
"Alternatively, are you sure your SOAP username and password are correct?"

could you please tell me which file can I edit the SOAP username and password. I have sugarcrm 6.5 running on ubuntu x64 server. i am a little lost with the SOAP authentication.  
Im also not able to find any "config.override.php" file on the server.

I am having the same issue as fromredtogreen when I install from the git hub

**Comment by blak3r** [comment] 2012-07-17 01:32
Hello, 

You have to do two things 
A) install the asteriskLogger from the sugar 6.5 branch
B) you can add the aforementioned line to your config.ini instead. 

Hope this helps. 

~blake

**Comment by thedeepak** [comment] 2012-07-17 06:38
Hi,

This module is fantastic, works fine with Sugar6.5 PRO after updating the changes specific to this version. But the problem we are getting is :

We are not being able to add Dashlets on home page.

When we tried to see the erroron firebug console  it says :

SUGAR.mySugar.currentDashlet is null
...te('id');dashlet_guid=current_dashlet_id.substr('dashlet_entire'.length);if(data...

Can you suggest us how we can sort this out ?
Is there any conflicting file that is disturbing SugarJS ?
Note : If we go and disable this MODULE from module loader, again we can add dashlets.

Thanks

**Comment by blak3r** [comment] 2012-07-17 07:11
Thanks! Does you AsteriskJS include jQuery?

That's what causes most issues. Do just double check. The version check is really hacky it's like an if sugar version equals "6.5.0". Been really busy. 

Do you have any plugins installed that  could be conflicting?

~blake

**Comment by sayantandas** [comment] 2012-07-17 08:12
Hi Blake,

THank you for your reply. I downloaded the zip file from the sugarcrm 6.5 branch on git hub and installed it through the modules loader on sugar crm. Now, after installing, I opened the cli and tried running the asteriskLogger.php file. Here is the output

 php sugarcrm/custom/modules/Asterisk/asteriskLogger.php

*******\* Asterisk Logger Starting **************

# Sugar root set to [/var/www/sugarcrm/custom/modules/Asterisk/../../../]

Logging to: /var/log/asterisk-sugarcrm.log

# Callout prefix is [1]

# Callin prefix is [+1]

asteriskMatchInternal = /^(sip\/[1-9][0-9][0-9]?[0-9]?-|Local)/i

# (Config processed)

Selecting DB Name: sugarcrm
! Trying SOAP login endpoint=[http://xxx.xxx.x.xx/sugarcrm/soap.php] user=[admin] password=[bee29934627d7deadb4e4d5baf923ad7]
PHP Warning:  Attempt to modify property of non-object in /var/www/sugarcrm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/sugarcrm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/sugarcrm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/sugarcrm/include/nusoap/nusoap.php on line 6160
! Soap login failed!
Array
(
    [id] => -1
    [error] => Array
        (
            [number] => 10
            [name] => Invalid Login
            [description] => Login attempt failed please check the username and password
        )

)
! FATAL: SOAP login failed, something didnt get set by login... check your site_url:-1 user=admin GUID=-1

I can see the ASTERISK SugarCRM Connector GUI management on the SugarCRM admin screen, but I can only change the Asterisk soap-user name and not the password.  Here is the screenshot : http://dl.dropbox.com/u/526059/Selection_096.png

Also, you mentioned earlier  about config.ini, but there is no config.ini file in my system. Did you mean config.php for sugarcrm?

**Comment by thedeepak** [comment] 2012-07-17 10:02
Hi Blake,

Thank  you for reply but I can verify that :

-we have updated the updates you have provided on 6.5 branch
-we don't have inclusion of JQuery file on Asterisk files (Commit changes also has removed plus we have rechecked the code too and there is no issue with that)

Now only the problem is with Adding dashlet as I mentoned earlier, moreover, as far as there is concern about other extensions , we have not installed any extensions as we are first trying with the SugarCRM6.5.0 fresh copy.

It would be really nice if someone could figure this out.

Thank you,
Deepak

**Comment by blak3r** [comment] 2012-07-17 14:04
I bet there is some action that isn't being handled. At the top of AsteriskJS you'll see a monster if statement with about 10 conditions.  It prevents the code from being included on ajax calls. 

Use firebug or chrome to see what Ajax calls are being made when you click add dash let. 

~blake

**Comment by blak3r** [comment] 2012-07-17 14:09
I explained all this in a thread. Just search issues for soap password and you should find it. 

Soap password isn't in config GUI. Have to add it to config.ini or config.override. Doesn't matter which. 

~blake

**Comment by sayantandas** [comment] 2012-07-17 20:43
Thanks so much blake. I am able to login now. I will try to get the dial buttons working now. :)

**Comment by blak3r** [comment] 2012-07-17 20:58
@sayantandas Do you have the issue that @thedeepak Had related to adding dash lets?  Anyone Feel free to chime in here.

**Comment by sayantandas** [comment] 2012-07-17 22:40
@blak3r : I have not added dashlets as yet, but I am getting a new error message 

 Successfully opened socket connection to 127.0.0.1:5038
! AMI Login action returned with rc=Asterisk Call Manager/1.0

[2012-07-17 23:33:36]
! --- Event -----------------------------------------------------------
!                Event -->  
! ---------------------------------------------------------------------
[2012-07-17 23:34:36] Timeout or Error
[2012-07-17 23:35:36] Timeout or Error
[2012-07-17 23:36:36] Timeout or Error
[2012-07-17 23:37:36] Timeout or Error

I have not yet looked the error message in details.

**Comment by blak3r** [comment] 2012-07-18 01:03
That's not an error. That happens every minute of no activity. 

~blake

**Comment by sayantandas** [comment] 2012-07-18 17:07
@blak3r : Ok, i can now see the the calls flowing through on the terminal.   I am able to get the dial buttons without much effort in as well now. Next is testing calls.

**Comment by blak3r** [comment] 2012-07-19 18:43
@sayantandas could you try creating a dashlet?  I'd help @thedeepak isolate if the issue is something with his install or not.

**Comment by blak3r** [comment] 2012-07-21 18:05
@thedeepak I just tried adding a dashlet to my fresh 6.5.0 PRO instance with demo data loaded.  I am able to add dashlets.  So, don't know what to tell ya.

When you click "Add Dashlet" it kicks off an ajax request to:
http://<server>/sugarcrm/index.php?to_pdf=true&module=Home&action=DynamicAction&DynamicAction=dashletsDialog

Since the to_pdf=true is in there, non of the asterisk js stuff gets loaded in that request which could interfere.  Do some more debugging with firebug to see if in Create Dashlet response there is stuff being returned that shouldn't be.

**Comment by thedeepak** [comment] 2012-07-25 05:55
@blak3r Thank you for the confirmation...and apologies for late response as I was away for some days. I'll give a fresh try again and can verify that.

**Comment by edokid** [comment] 2012-07-30 00:50
Hi all, I'm finally back and able to try this again but still can't make it work.  When I used the previous version with 6.5 it did work but the interface was all messed up as per my original post.  I uninstalled the module completely and installed the 7/22 version however I'm getting the same error above, it says:

! Trying SOAP login endpoint=[http:///10.0.0.50/soap.php] user=[jsmith] password=[630e53330e3f8265f13230c270448895]
! FATAL: SOAP login failed, something didnt get set by login... check your site_url: user=jsmith GUID=

I'm setting the SOAP password using the GUI in the box for it, and under config_override.php under asterisk_soappassword it shows the password already there that I entered from the GUI, so the username and password are correct.  

Do I need to manually add any of the files from here or does the 7/22 version have them all fixed?  Just to confirm, the SOAP username and password are the same as a SugarCRM admin user correct?

**Comment by edokid** [comment] 2012-07-30 00:54
Okay so weird I just fixed it, as soon as I posted that I noticed it said trying http:/// with 3 /'s but under config.php I have it as http://10.0.0.50 so I changed it to http:/10.0.0.50 and now it works fine :S

**Comment by sayantandas** [comment] 2012-07-31 17:49
@blak3r @thedeepak , i have just tested with sugarcrm 6.5.0 and yaai 2.4.0, i am able to add dashlets just fine. I added the calendar dashlet without crashing.

**Comment by blak3r** [comment] 2012-08-03 21:33
@sayantandas Thanks for testing!

**Comment by sayantandas** [comment] 2012-08-09 10:28
@blak3r  No problem. I have question regarding asterisk connectivitiy. We are currently using asterisk on the server and use softphones to connect to asterisk. the softphone login to asterisk is cc150 and password is test.  so now, what should i put as the asterisk extension in the configuration file of the asterisk connector?

**Comment by blak3r** [comment] 2012-08-09 12:07
Are you talking about the administrative config?

You don't need to use your soft phone credentials anywhere in yaai. You just need configure AMI. 

~blake

**Comment by blak3r** [comment] 2012-08-31 06:35
Problem is a SOAP issue. Meaning the script can't talk to
Your CRM.  It's not failing to connect to asterisk. 

Network security maybe?

~blake

**Comment by sayantandas** [comment] 2012-08-31 11:19
@blak3r : Two interesting things. 1) I was able to connect using v2.4.0 of your module. I upgraded to the latest version (2.4.1) and after that it stopped connecting. I downgraded to 2.4.0 but no avail. 
2)  I can  still connect to asterisk via telnet from the new server  and there is no firewall on either servers.

**Comment by blak3r** [comment] 2012-10-02 01:21
@sayantandas did you ever get it working?  I'm closing this issue as Support for Sugar v6.5 was added a while ago.

**Closed as completed by blak3r** 2012-10-02 01:21 UTC
Labels: bug, enhancement
